# Configuracoes compartilhadas
spring.application.name=adm-soler

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Server
server.port=8080

# Ativar perfil padrao
spring.profiles.active=h2
